version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - freecodecamp
  api:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=dev-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - dev-db
    networks:
      - freecodecamp

volumes:
  postgres-data:

networks:
  freecodecamp:
